# Generated by Django 3.0.7 on 2020-07-04 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('busy', 'Busy'), ('off', 'Off')], default='off', max_length=10, verbose_name='Sex')),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True, verbose_name='User')),
                ('request_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 20, 17, 57, 400941), null=True, verbose_name='Request Date')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('ip', models.CharField(max_length=15, verbose_name='IP')),
                ('user_agent', models.CharField(max_length=200, verbose_name='User Agent')),
                ('referer', models.CharField(max_length=200, verbose_name='Referer')),
                ('room_uuid', models.UUIDField(default=uuid.UUID('e5c08a2c-5521-4b5b-99d9-da38fec8c81d'), verbose_name='Room UUID')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Operator', verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['request_date', 'operator', 'start_date'],
            },
        ),
    ]
