# Generated by Django 3.0.7 on 2020-07-06 14:59

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 6, 14, 59, 0, 713213), null=True, verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='room_uuid',
            field=models.UUIDField(default=uuid.UUID('55a10c81-239f-4403-b44f-fad451ce19e0'), unique=True, verbose_name='Room UUID'),
        ),
    ]
