# Generated by Django 3.0.7 on 2020-07-15 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200713_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.System', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='session',
            name='request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 15, 11, 20, 22, 568325), null=True, verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='room_uuid',
            field=models.UUIDField(default=uuid.UUID('2351f88d-276f-4526-aa9d-bcf818275d81'), unique=True, verbose_name='Room UUID'),
        ),
    ]
