# Generated by Django 3.0.7 on 2020-07-16 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200715_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.System', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='session',
            name='request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 16, 15, 43, 8, 731227), null=True, verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='room_uuid',
            field=models.UUIDField(default=uuid.UUID('09fa113c-bcae-4f58-9039-cea57d233571'), unique=True, verbose_name='Room UUID'),
        ),
    ]
