# Generated by Django 3.0.7 on 2020-07-16 16:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200716_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 16, 16, 2, 35, 722172), null=True, verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='room_uuid',
            field=models.UUIDField(default=uuid.UUID('7fd4ed4f-c60d-41c1-b1bf-82bb1bff871f'), unique=True, verbose_name='Room UUID'),
        ),
        migrations.AlterUniqueTogether(
            name='operator',
            unique_together={('name', 'system')},
        ),
    ]
